name: Vulnerability Scan

on:
  push

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        
      - name: Pull docker image
        run: docker build -t sample .

      - uses: homoluctus/gitrivy@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: sample
